version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo not installing anything else
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - node -v
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build-$REACT_ENV

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing build to s3 bucket
      - aws s3 sync build/ s3://$S3_BUCKET_NAME
      - echo Invalidating old objects of s3 bucket from cloud front distribution
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --path '/*'
